// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhdijubftjysqsdpblph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoZGlqdWJmdGp5c3FzZHBibHBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MzI4NzEsImV4cCI6MjA3MTQwODg3MX0.NsIY9---aCHN4aypZWXWXPTReC3SQ_WzZokhUQyRq3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});